### ISSUE TITLE
Can't launch

### ISSUE THREAD

**Issue by thecmdrunner** [remotion-dev/template-remix#4]
# What
Can't get the remix template to work at all (tried npm, pnpm, bun)
![image](https://github.com/remotion-dev/template-remix/assets/38887390/7f229362-9ca8-4e2f-9d0e-b0e7ce00805c)

```shell
✘ [ERROR] Could not resolve "react/jsx-dev-runtime"

    app/routes/index.tsx:99:4:
      99 │         <Player
         ╵         ^

  The Yarn Plug'n'Play manifest forbids importing "react" here because it's not listed as a dependency of this package:

    ../.pnp.cjs:38:33:
      38 │           "packageDependencies": [\
         ╵                                  ~~

  You can mark the path "react/jsx-dev-runtime" as external to exclude it from the bundle, which will remove this error.


💿 Rebuilt in 384ms
Remix App Server started at http://localhost:3000 (http://10.191.0.102:3000)
Error: Cannot find module '/home/thecmdrunner/remix-test/api/index.js'
Require stack:
- /home/thecmdrunner/remix-test/node_modules/@remix-run/serve/dist/index.js
- /home/thecmdrunner/remix-test/node_modules/@remix-run/dev/dist/devServer/serve.js
- /home/thecmdrunner/remix-test/node_modules/@remix-run/dev/dist/cli/commands.js
- /home/thecmdrunner/remix-test/node_modules/@remix-run/dev/dist/cli/run.js
- /home/thecmdrunner/remix-test/node_modules/@remix-run/dev/dist/cli/index.js
- /home/thecmdrunner/remix-test/node_modules/@remix-run/dev/dist/index.js
- /home/thecmdrunner/remix-test/node_modules/@remix-run/dev/dist/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Function.Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at /home/thecmdrunner/remix-test/node_modules/@remix-run/serve/dist/index.js:43:17
    at Layer.handle [as handle_request] (/home/thecmdrunner/remix-test/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/thecmdrunner/remix-test/node_modules/express/lib/router/route.js:144:13)
    at next (/home/thecmdrunner/remix-test/node_modules/express/lib/router/route.js:140:7)
    at next (/home/thecmdrunner/remix-test/node_modules/express/lib/router/route.js:140:7)
    at next (/home/thecmdrunner/remix-test/node_modules/express/lib/router/route.js:140:7)
GET / 500 - - 2.311 ms
```

# How to reproduce

1. `npm create video` - select remix template
2. `npm run dev`

**Comment by JonnyBurger** [comment]
I wonder if it has to do with Yarn 3 still? That adds another file to the project automatically.. might also be worth trying out @florentpergoud's V2 upgrade
